//v2
export enum QUERY_KEYS {
  //User key
  GET_USERS_V2 = "GET_USERS_V2",
  GET_STAFFS_V2 = "GET_STAFFS_V2",
  GET_ADDRESS_INTO_V2 = "GET_ADDRESS_INTO_V2",

  //Product key
  GET_PRODUCTS_V2 = "GET_PRODUCTS_V2",

  //Auction key
  GET_AUCTIONS_V2 = "GET_AUCTIONS_V2",
  GET_TBL_AUCTIONS_V2 = "GET_TBL_AUCTIONS_V2",

  //Wallet
  GET_WALLET_V2 = "GET_WALLET_V2",

  //ORDER
  GET_ORDERS_V2 = "GET_ORDERS_V2",
}
